version: "3.9"

services:
  api:
    build: ./freelanceNew
    container_name: freelance-api
    restart: unless-stopped
    environment:
      - ConnectionStrings__ApplicationDbContext=User ID=postgres;Password=karakuli;Host=46.17.248.176;Port=5432;Database=freelanceNew
    ports:
      - "8080:5000"
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: freelanceNew
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: karakuli
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: nginx_gateway
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api

volumes:
  pgdata: